export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { content, title } = req.body
  if (!content) return res.status(400).json({ error: 'content required' })

  // Generate a clean HTML page that prints as PDF
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title || 'EduBot Answer'}</title>
<style>
  body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; line-height: 1.7; font-size: 14px; }
  h1 { color: #1d4ed8; border-bottom: 2px solid #1d4ed8; padding-bottom: 8px; }
  h2 { color: #1d4ed8; margin-top: 24px; }
  h3 { color: #4a4a4a; }
  strong { color: #1a1a1a; }
  code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; font-size: 12px; }
  .meta { color: #888; font-style: italic; font-size: 12px; margin-bottom: 30px; }
  sup { font-size: 10px; }
</style>
</head>
<body>
<h1>${title || 'EduBot Answer'}</h1>
<div class="meta">Generated by EduLink EduBot · ${new Date().toLocaleDateString()}</div>
${content
  .split('\n')
  .map(line => {
    const t = line.trim()
    if (!t) return '<br>'
    if (t.startsWith('## ')) return `<h2>${t.slice(3)}</h2>`
    if (t.startsWith('### ')) return `<h3>${t.slice(4)}</h3>`
    if (t.startsWith('- ') || t.startsWith('• ')) return `<li>${t.slice(2)}</li>`
    const formatted = t
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/`(.*?)`/g, '<code>$1</code>')
      .replace(/(\w)\^(\d)/g, '$1<sup>$2</sup>')
      .replace(/\\times/g, '×').replace(/\\div/g, '÷')
    return `<p>${formatted}</p>`
  })
  .join('\n')}
</body>
</html>`

  // Return as HTML that the client can print/save as PDF
  res.setHeader('Content-Type', 'text/html')
  res.setHeader('Content-Disposition', 'attachment; filename="EduBot_Answer.html"')
  res.send(html)
}