import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  const { content, title } = req.body
  if (!content) return res.status(400).json({ error: 'content required' })

  const lines = content.split('\n')
  const children = []

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: title || 'EduLink Document', bold: true, size: 36, color: '1d4ed8' })],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Generated by EduLink · ${new Date().toLocaleDateString()}`, size: 18, color: '888888', italics: true })],
      spacing: { after: 400 },
    })
  )

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) { children.push(new Paragraph({ spacing: { before: 100, after: 100 } })); continue }

    if (trimmed.startsWith('# ')) {
      children.push(new Paragraph({ children: [new TextRun({ text: trimmed.slice(2), bold: true, size: 32, color: '1d4ed8' })], heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 150 } }))
    } else if (trimmed.startsWith('## ')) {
      children.push(new Paragraph({ children: [new TextRun({ text: trimmed.slice(3), bold: true, size: 28, color: '2563eb' })], heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 } }))
    } else if (trimmed.startsWith('### ')) {
      children.push(new Paragraph({ children: [new TextRun({ text: trimmed.slice(4), bold: true, size: 24, color: '4f46e5' })], heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } }))
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      const text = trimmed.slice(2)
      const runs = parseBold(text)
      children.push(new Paragraph({ children: runs, bullet: { level: 0 }, spacing: { before: 60, after: 60 } }))
    } else if (/^\d+\. /.test(trimmed)) {
      const text = trimmed.replace(/^\d+\. /, '')
      const runs = parseBold(text)
      children.push(new Paragraph({ children: runs, numbering: { reference: 'default', level: 0 }, spacing: { before: 60, after: 60 } }))
    } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
      children.push(new Paragraph({ children: [new TextRun({ text: trimmed.slice(2, -2), bold: true, size: 22 })], spacing: { before: 80, after: 60 } }))
    } else {
      const runs = parseBold(trimmed)
      children.push(new Paragraph({ children: runs, spacing: { before: 60, after: 60 } }))
    }
  }

  const doc = new Document({
    numbering: {
      config: [{
        reference: 'default',
        levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.LEFT }],
      }],
    },
    sections: [{ properties: {}, children }],
  })

  const buffer = await Packer.toBuffer(doc)
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
  res.setHeader('Content-Disposition', `attachment; filename="${(title || 'EduLink').replace(/[^a-z0-9]/gi,'_')}.docx"`)
  res.send(buffer)
}

function parseBold(text) {
  const parts = text.split(/\*\*(.*?)\*\*/g)
  return parts.map((part, i) => new TextRun({ text: part, bold: i % 2 === 1, size: 22 }))
}